# Generated by Django 5.2.7 on 2026-01-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(default='#ff7c23', help_text='Culoare HEX, ex: #ff7c23', max_length=20),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(default='fa-tag', help_text='Icon FontAwesome, ex: fa-dumbbell', max_length=50),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='descriere',
            field=models.TextField(default='Descriere implicita categorie'),
            preserve_default=False,
        ),
    ]
